from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from typing import Optional


class UserProfile(models.Model):
    """
    Extended user profile with role-based access control.
    
    Automatically created for each User via post_save signal.
    Defines three roles for the drilling report system:
    - Supervisor: Can create and manage drill shift reports
    - Manager: Can review and approve/reject shift reports
    - Client: Can view approved reports and BOQ data
    
    Attributes:
        user: One-to-one relationship with Django User model
        role: User's role in the system (supervisor/manager/client)
        company: Optional company name
        phone: Optional phone number
    """
    ROLE_SUPERVISOR = 'supervisor'
    ROLE_MANAGER = 'manager'
    ROLE_CLIENT = 'client'
    
    ROLE_CHOICES = [
        (ROLE_SUPERVISOR, 'Supervisor'),
        (ROLE_MANAGER, 'Manager'),
        (ROLE_CLIENT, 'Client'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=ROLE_SUPERVISOR)
    company = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=20, blank=True)

    def get_role_display(self) -> str:
        """Get the display value for the role field. Auto-generated by Django."""
        return dict(self.ROLE_CHOICES).get(self.role, self.role)
    
    def __str__(self) -> str:
        return f"{self.user.username} ({self.get_role_display()})"
    
    @property
    def is_supervisor(self):
        """Check if user has supervisor role."""
        return self.role == self.ROLE_SUPERVISOR
    
    @property
    def is_manager(self):
        """Check if user has manager role."""
        return self.role == self.ROLE_MANAGER
    
    @property
    def is_client(self):
        """Check if user has client role."""
        return self.role == self.ROLE_CLIENT


# Signal to create/update UserProfile when User is created/updated
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Signal handler to automatically create or update UserProfile.
    
    Creates a new UserProfile when a User is created.
    Saves the profile when an existing User is updated.
    
    Args:
        sender: The User model class
        instance: The actual User instance being saved
        created: Boolean indicating if this is a new User
        **kwargs: Additional signal arguments
    """
    if created:
        UserProfile.objects.create(user=instance)
    else:
        instance.profile.save()