# Generated by Django 5.0 on 2025-11-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drillingprogress_penetration_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillshift',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day Shift (07:00 - 19:00)'), ('night', 'Night Shift (19:00 - 07:00)')], default='day', max_length=16),
        ),
    ]
