# Generated by Django 5.0 on 2025-11-06 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drillshift_shift_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='drillingprogress',
            name='core_gain',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Core gain in meters', max_digits=10),
        ),
        migrations.AddField(
            model_name='drillingprogress',
            name='core_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Core loss in meters', max_digits=10),
        ),
        migrations.AddField(
            model_name='drillingprogress',
            name='hole_number',
            field=models.CharField(blank=True, help_text='Hole identifier (e.g., BH-001)', max_length=50),
        ),
        migrations.AddField(
            model_name='drillingprogress',
            name='recovery_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='driller_name',
            field=models.CharField(blank=True, help_text='Driller', max_length=255),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='helper_names',
            field=models.CharField(blank=True, help_text='Helper names (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='Shift Supervisor', max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes (required)'),
        ),
        migrations.AlterField(
            model_name='drillingprogress',
            name='penetration_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated (m/hr)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.client'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('gyro', 'Gyro Survey'), ('camera', 'Camera Survey'), ('ongoing', 'Ongoing Survey'), ('magnetic', 'Magnetic Survey'), ('other', 'Other')], default='ongoing', max_length=32)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in meters', max_digits=10)),
                ('dip_angle', models.DecimalField(decimal_places=2, help_text='Dip angle in degrees', max_digits=5)),
                ('azimuth', models.DecimalField(decimal_places=2, help_text='Azimuth in degrees (0-360)', max_digits=6)),
                ('findings', models.TextField(blank=True, help_text='Survey results and observations')),
                ('surveyor_name', models.CharField(blank=True, max_length=255)),
                ('survey_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.drillingprogress')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.drillshift')),
            ],
            options={
                'ordering': ['depth'],
            },
        ),
    ]
