# Generated by Django 5.0 on 2025-11-06 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_drillingprogress_core_gain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for client login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='client_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='client_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='client_comments',
            field=models.TextField(blank=True, help_text='Client feedback or rejection reason'),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='client_status',
            field=models.CharField(blank=True, choices=[('pending_client', 'Pending Client Approval'), ('client_approved', 'Client Approved'), ('client_rejected', 'Client Rejected')], help_text='Client approval status', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='submitted_to_client_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
