# Generated by Django 5.0 on 2025-11-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_user_drillshift_client_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillshift',
            name='standby_client',
            field=models.BooleanField(default=False, help_text='Standby due to client reasons'),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='standby_client_reason',
            field=models.CharField(blank=True, choices=[('pad_preparation', 'Pad Preparation'), ('order_by_client', 'Order by Client'), ('site_access', 'Site Access Issues'), ('client_delay', 'Client Delay'), ('other_client', 'Other (Client)')], max_length=50),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='standby_client_remarks',
            field=models.TextField(blank=True, help_text='Additional details about client standby'),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='standby_constructor',
            field=models.BooleanField(default=False, help_text='Standby due to constructor reasons'),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='standby_constructor_reason',
            field=models.CharField(blank=True, choices=[('mobilizing', 'Mobilizing'), ('demobilizing', 'Demobilizing'), ('safety_incident', 'Safety Incident'), ('equipment_breakdown', 'Equipment Breakdown'), ('maintenance', 'Maintenance'), ('weather', 'Weather Conditions'), ('other_constructor', 'Other (Constructor)')], max_length=50),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='standby_constructor_remarks',
            field=models.TextField(blank=True, help_text='Additional details about constructor standby'),
        ),
    ]
