# Generated by Django 5.0 on 2025-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drillshift_standby_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillshift',
            name='helper_names',
        ),
        migrations.AddField(
            model_name='drillshift',
            name='helper1_name',
            field=models.CharField(blank=True, help_text='Helper 1', max_length=255),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='helper2_name',
            field=models.CharField(blank=True, help_text='Helper 2', max_length=255),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='helper3_name',
            field=models.CharField(blank=True, help_text='Helper 3', max_length=255),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='helper4_name',
            field=models.CharField(blank=True, help_text='Helper 4', max_length=255),
        ),
    ]
