# Generated by Django 5.0 on 2025-11-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_drillshift_helper_names_and_more'),
    ]

    operations = [
    ]
