# Generated by Django 5.0 on 2025-11-06 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251106_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillingprogress',
            name='size',
            field=models.CharField(choices=[('PQ', 'PQ (85mm)'), ('HQ', 'HQ (63.5mm)'), ('NQ', 'NQ (47.6mm)'), ('BQ', 'BQ (36.5mm)'), ('AQ', 'AQ (27mm)')], default='HQ', help_text='Drill bit size', max_length=10),
        ),
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing_size', models.CharField(choices=[('2"', '2 inch'), ('3"', '3 inch'), ('4"', '4 inch'), ('6"', '6 inch'), ('8"', '8 inch'), ('10"', '10 inch'), ('12"', '12 inch')], help_text='Casing diameter', max_length=10)),
                ('casing_type', models.CharField(choices=[('pvc', 'PVC'), ('steel', 'Steel'), ('hdpe', 'HDPE'), ('fiberglass', 'Fiberglass'), ('other', 'Other')], default='pvc', help_text='Casing material type', max_length=32)),
                ('start_depth', models.DecimalField(decimal_places=2, help_text='Starting depth in meters', max_digits=10)),
                ('end_depth', models.DecimalField(decimal_places=2, help_text='Ending depth in meters', max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, help_text='Total length in meters', max_digits=10)),
                ('remarks', models.TextField(blank=True, help_text='Notes about casing installation')),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casings', to='core.drillshift')),
            ],
            options={
                'ordering': ['start_depth'],
            },
        ),
    ]
