# Generated by Django 5.0 on 2025-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_drillingprogress_size_casing'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillingprogress',
            name='core_tray_image',
            field=models.ImageField(blank=True, help_text='Photo of core tray (optional)', null=True, upload_to='core_trays/%Y/%m/%d/'),
        ),
    ]
