# Generated by Django 5.0 on 2025-11-22 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drillingprogress_core_tray_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('recovery', 'Low Core Recovery'), ('rop_drop', 'ROP Drop'), ('downtime', 'Excessive Downtime'), ('bit_failure', 'Bit Failure Warning')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Alert value (%, hours, etc)', max_digits=10, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold breached', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.drillshift')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'is_active'], name='core_alert_alert_t_b49238_idx'), models.Index(fields=['severity', 'is_active'], name='core_alert_severit_d66c7e_idx')],
            },
        ),
    ]
