# Generated by Django 5.0 on 2025-11-22 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drillshift',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when manager approved shift', null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='project_code',
            field=models.CharField(blank=True, help_text='Internal project or contract code', max_length=64),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Client PO / authorization reference', max_length=64),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when shift was first submitted', null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='target_meters_per_shift',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target meters drilled per shift', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='target_recovery_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target recovery percentage for this project', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='drillshift',
            name='target_rop',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target average rate of penetration (m/hr)', max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='drillshift',
            index=models.Index(fields=['project_code'], name='core_drills_project_13a949_idx'),
        ),
    ]
